spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mzc_order?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qwer
  application:
    name: order-impl

mybatis-plus:
  configuration:
    map-undersource-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: mzc.mall.order.dataobject

#dubbo
dubbo:
  application:
    name: order-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: mzc.mall.order.service
  provider:
    filter: -exception
  consumer:
    timeout: 120000   #设置长一点，方便调试
  ProductSpuService:
    version: 1.0.1
